export const keys = {
    // REACT_APP_OPENAI_API_KEY: process.env.REACT_APP_OPENAI_API_KEY || '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'
    REACT_APP_OPENAI_API_KEY: process.env.REACT_APP_OPENAI_API_KEY || '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'
}